# Generated by Django 3.2.6 on 2021-08-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer_description', models.TextField(max_length=2000)),
                ('best_answer', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_title', models.TextField(max_length=200)),
                ('question_description', models.TextField(max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
