# Generated by Django 3.2.6 on 2021-08-12 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('answer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('best_answer', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=200)),
                ('question_description', models.CharField(max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer_parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explain.answer')),
                ('question_parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explain.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explain.question'),
        ),
    ]
